const fakedata = [
  {
    client: "CR7",
    destination: "peronio 123, CABA",
    is_delivered: false,
    package_weight: 20.0,
    deadline_date: "2023-10-10",
    quantity: 1,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Messi",
    destination: "mesiland 2050, CABA",
    is_delivered: false,
    package_weight: 60.0,
    deadline_date: "2023-10-10",
    quantity: 2,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Tevez",
    destination: "industria 2219, CABA",
    is_delivered: false,
    package_weight: 20.9,
    deadline_date: "2023-10-10",
    quantity: 3,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "La Mole Moli",
    destination: "telefe al 0800, CABA",
    is_delivered: false,
    package_weight: 15.0,
    deadline_date: "2023-10-10",
    quantity: 2,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Carlos Melconian",
    destination: "peronioes 123, CABA",
    is_delivered: false,
    package_weight: 20.0,
    deadline_date: "2023-10-10",
    quantity: 1,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Antonella Messi",
    destination: "mesiland 2050, CABA",
    is_delivered: false,
    package_weight: 60.0,
    deadline_date: "2023-10-10",
    quantity: 2,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Ricardo Fort",
    destination: "felfort 2219, CABA",
    is_delivered: false,
    package_weight: 20.9,
    deadline_date: "2023-10-10",
    quantity: 3,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Michael Jackson",
    destination: "cementerio de recoleta, CABA",
    is_delivered: false,
    package_weight: 15.0,
    deadline_date: "2023-10-10",
    quantity: 2,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Mercedes sosa",
    destination: "José Uriburu 1792, C1114 CABA",
    coords: { lat: -34.5887007, lng: -58.3966804 },
    is_delivered: false,
    package_weight: 15.0,
    deadline_date: "2023-10-10",
    quantity: 2,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Menem",
    destination: "Balcarce 78, C1064 CABA",
    coords: { lat: -34.6080512, lng: -58.3728527 },
    is_delivered: false,
    package_weight: 20.0,
    deadline_date: "2023-10-10",
    quantity: 1,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Monserrat",
    destination: "Monserrat, Buenos Aires",
    is_delivered: false,
    package_weight: 60.0,
    deadline_date: "2023-10-10",
    quantity: 2,
    quantity_taked: 0,
    additional_information: "",
    coords: { lat: -34.6125406, lng: -58.3896419 },
  },
  {
    client: "El papa francisco",
    destination: "Av. Avellaneda 2804-2702, C1406FYZ CABA",
    coords: { lat: -34.625717, lng: 58.4721635 },
    is_delivered: false,
    package_weight: 20.9,
    deadline_date: "2023-10-10",
    quantity: 3,
    quantity_taked: 0,
    additional_information: "",
  },
  {
    client: "Martin insaurralde",
    destination: "Gallo 1455, Buenos Aires, Argentina",
    is_delivered: false,
    package_weight: 15.0,
    deadline_date: "2023-10-10",
    quantity: 2,
    quantity_taked: 0,
    additional_information: "",
    coords: { lat: -34.5935069, lng: -58.4123182 },
  },
];

export default fakedata;
