paths:
  /user:
    get:
      summary: Obtiene la lista de deliveryMans
      responses:
        '200':
          description: Respuesta exitosa
      content:
        application/json:
          schema:
            $ref: './deliveryManSchema.yml'
