openapi: 3.0.3
info:
  title: API De Fast Delivery
  description: Esta API se encarga de manejar los datos de Fast Delivery
  version: 1.11.2
servers:
  - url: http://localhost:3001
paths:
  /users:
    $ref: './userDocs/userRoutes.yml'

  /packages:
    $ref: './packagesDocs/packages-routes.yml'

  /deliveryman:
    $ref: './deliverymanDocs/deliveryman-routes.yml'
